name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  make-ci:
    name: make-ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Copy env
        run: cp .env.example .env

      - name: make ci
        run: make ci
